[package]
workspace = ".."
name = "embedded-sprites"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
embedded-graphics = "0.7.1"
embedded-sprites-proc-macro  = {version = "0.1.0", path = "../proc-macro"}
fixedbitset = { version = "0.4.2", default-features = false }
thiserror = "1.0.38"

[dev-dependencies]
konst = "0.3.4"
embedded-graphics-simulator = "0.4.0"
